### PR TITLE
Added English Translated User Manual [Fixes Issue #14]

### PR DESCRIPTION
**Pull request by GDGouravDey**
Fixes: #14

Added the English Translations of the User Manual in .docx and .pdf format. 

File Directory: docs/manual/

### CODE REVIEW

**Review by GeorgeApos — CHANGES_REQUESTED** [review]
There is a problem with Contents, please fix that. They have to be in a seperated page, not in the first one,

**Comment by GDGouravDey** [comment]
Thanks for pointing out the problem. I have made the necessary changes as stated by you, by taking the Contents section to the 2nd page.

Please do reply if any more changes are required to be done. I have only added the English translation in this commit. If it is required, I can also add the original Greek version of the User Manual.

**Comment by GeorgeApos** [comment]
@GDGouravDey unfortunately this needs to be checked by a Greek and make the appropriate changes. There are some problems with the translation. 

I am suggesting to put this in archive and let someone from the team to get involved.

**Comment by GeorgeApos** [comment]
Thank you for your effort, I will be resolving these issues.

**Pull request merged**
