### PR TITLE
fix(useDepCode, useDepName): object instead of tuple

### PR DESCRIPTION
**Pull request by papsavas**
- fixes `useGraduationLink` usage
- converts `useDepName` & `useDepCode` hooks to return an object instead of a tuple
  - Tuple hooks are preferred only for react states due to their unique `[value, setter]` nature. 
  - Tuples break inference confusing each value to either one (solved with `as const` in typescript but may excessively specify types)
  - Tuples are not great dx for more than 2 arguments.

given a tuple hook with 3 variables:
```js
const [_, _, arg3] = useMyHook()
```

objects will resolve it to:
```js
// + name inference
const { arg3 } = useMyHook()
```

### CODE REVIEW

**Review by GeorgeFkd — APPROVED** [review]

**Comment by GeorgeFkd** [comment]
Is this tested for all departments and department specific-pages? (Graducation,Exams Schedule,Course Schedule,Academic Personnel)

**Comment by papsavas** [comment]
this should be fixed in https://github.com/Open-Source-UoM/MyUoM/pull/17/commits/7d3472c7406db0f9ad2760909568ab5b4bd06116 & https://github.com/Open-Source-UoM/MyUoM/pull/17/commits/32d5065704e172f82556d8af6d152591a6422d94

**Comment by shivam-sharma7** [comment]
@papsavas would you squash your commits? becasue your PR is solving one issue so one commit for one issue would be better

**Comment by papsavas** [comment]
@shivam-sharma7 This PR solves 2 issues. In any case though, PR history should be preserved and the squashing should occur when maintainers merge. This way, main's history behaves as clean index point to each PR where you can inspect detailed changes by commit

**Comment by shivam-sharma7** [comment]
@papsavas They are using `Create a merge commit` technique. Would you like to describe two issue which you're trying to fix.

**Comment by GeorgeApos** [comment]
Can you resolve these conflicts?

**Comment by papsavas** [comment]
@GeorgeApos i think we're good

**Comment by GeorgeApos** [comment]
Thank you @papsavas

**Pull request merged**
