### PR TITLE
Added English Language Redirection

### LINKED ISSUE #80: Wrong redirection links when application's language is English
When the language of the application is English, all the redirection links refer to the Greek version of each Department.
Example: 
(Department selected is Applied Informatics)

When clicking on Student Care:
image

User gets redirected to:
image
Which is the Greek version of student care.

Instead, users should be redirected to the English version of the Department's website. 
The same rule applies to any redirection where an English version is available on the Department's website.

### PR DESCRIPTION
**Pull request by giomellios**
Fixes #80 

For each external link where an English version of the site was both **available** and **up-to-date** (in many cases, although an English version existed, the content was last updated in 2023 or 2022), an appropriate redirection was included.

Also fixed some wrong redirection links.

### CODE REVIEW

**Review by GeorgeApos — CHANGES_REQUESTED** [review]
Please check all the links to redirect to English links, for example Applied Informatics Announcements redirect to Greek link.

**Comment by giomellios** [comment]
@GeorgeApos In many cases (including the one that you mentioned), there was not an available English version of the corresponding MenuBox. If you navigate manually to the English version of DAI, you will see that there is no such thing as "Announcements" ("Τα νέα του τμήματος" in Greek) available. In many other cases where the corresponding link exists, the content is really outdated as I mentioned before. That's the reason I handled these situations that way.

So, taking into consideration the above, should I change it or not?

**Comment by GeorgeApos** [comment]
@giomellios Can you mention which links are in Greek right now? I can provide the english one, it's kinda tricky.

**Comment by giomellios** [comment]
@GeorgeApos 
The Greek links that I did not find an English version of them:
- Course Schedules of all departments
- Exams Schedules of all departments
- The Graduation page of all departments
- Announcements page of all departments

Also, from the Other Services MenuBox:
In offices tab:
- http://www.perivpamak.gr/
In Student Clubs tab:
- https://www.uom.gr/aiesec (which is the only link that redirects to the www.uom.gr website)

**Comment by giomellios** [comment]
@GeorgeApos
The Greek links that I did not find an English version of them:

- Course Schedules of all departments
- Exams Schedules of all departments
- The Graduation page of all departments
- Announcements page of all departments

Also, from the Other Services MenuBox:
In offices tab:
- http://www.perivpamak.gr/
In Student Clubs tab:
- https://www.uom.gr/aiesec (which is the only link that redirects to the [www.uom.gr](http://www.uom.gr/) website)
- https://tedxuniversityofmacedonia.com/
- https://opensource.uom.gr/
- https://csc.uom.gr/new/
In Other Services tab:
- https://www.uom.gr/synhgoros-toy-foithth
- https://www.uom.gr/eif

Please provide me the redirection english links of the above ones that you think are most necessary.

**Comment by GeorgeApos** [comment]
Thank you, Here is what I found:

- Periv Pamak has no English version
- AIESEC: https://www.uom.gr/en/aiesec-10426
- TEDx has no English version
- Open Source has no English version
- CSC has no English version
- Synigoros has no English version
- EIF : https://www.uom.gr/en/eif

Damn, I didn't know that so many links are only in Greek. We will make contact with the University regarding this issue.
Add these 2 links and we won't close this issue until it's fixed.

**Comment by giomellios** [comment]
AIESEC link displays an (almost) empty page, that's the reason that I didn't change it: 
image

EIF is kind of outdated.

Should I still change the links?

**Comment by GeorgeApos** [comment]
Yes, because we will make a contact with the university to fix and update these links. From our side we need to provide the english version of the website.

**Review by GeorgeApos — APPROVED** [review]

**Pull request merged**
