### PR TITLE
CI: Add node.js github action, fixes #8

### LINKED ISSUE #8: CI: Add node.js github action
Add CI/CD feature for fast build, test and deploy application

### PR DESCRIPTION
**Pull request by shivam-sharma7**

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@GeorgeFkd @GeorgeApos this is important and we should have to give it first priority to merge

**Comment by GeorgeApos** [comment]
This needs further discussion with @GeorgeFkd and @Tsalmas-Anastasios

**Comment by shivam-sharma7** [comment]
Agree! take a look - https://github.com/orgs/open-source-uom/discussions/new?category=ideas

**Comment by shivam-sharma7** [comment]
@GeorgeApos Enable github action tab for this repo

**Pull request merged**
